version: "3.8"

services:
  model_predict:
    build:
      context: ./fast-api
      dockerfile: /Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/api-predict
    restart: always
